### ISSUE TITLE
Game crash by unicorn?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chubakur/wizards-magic2#10]
```
What steps will reproduce the problem?
1. Play? :P
What is the expected output? What do you see instead?
fervi@ThunderStorm:~/WizardsMagic$ ./WizardsMagic.py
JSON
Traceback (most recent call last):
  File "./WizardsMagic.py", line 331, in <module>
    start_game(ai=globals.ai)
  File "./WizardsMagic.py", line 273, in start_game
    globals.event_handler.event(event)
  File "/home/fervi/WizardsMagic/eventhandler.py", line 72, in event
    item.onmousedown()
  File "/home/fervi/WizardsMagic/completethecoursebutton.py", line 30, in onmousedown
    player.finish_turn()
  File "/home/fervi/WizardsMagic/player.py", line 160, in finish_turn
    me_finish_turn()
  File "/home/fervi/WizardsMagic/player.py", line 118, in me_finish_turn
    kill = card.attack()
  File "/home/fervi/WizardsMagic/cards.py", line 197, in attack
    self.run_attack_animation()
  File "/home/fervi/WizardsMagic/cards.py", line 190, in run_attack_animation
    attack_animation = animations.CustomAnimation(self.image,cardbox_location) #Instantiating a animation object
AttributeError: 'Unicorn' object has no attribute 'image'

What version of the product are you using? On what operating system?
3.1.20 on Lubuntu 13.04
```

Original issue reported on code.google.com by `fervidoc...@gmail.com` on 9 Jan 2013 at 12:16

**Comment by sandrobonazzola** [comment]
I've seen this today as well, looks like a call to run_attack_animation() is issued after a call to die() which delete self.image.
